### PR TITLE
first set of host spec tests

### PR DESCRIPTION
**Pull request by tuxmea**
already has some code fixes
ugly hack for puppet 4.10.4 and later regarding sort_merged_array
spelling

### CODE REVIEW

**Comment by alvagante** [comment]
Wonderful,
but the hack in the main manifests/site.pp and an extra layer in profile's hierarchy is really ugly,
what happens when you set sort_merged_arrays on Puppet 4.10? It's ignored or an error is thrown?
Otherwise I wonder if it makes  sense to remove that option completely.

**Comment by tuxmea** [comment]
Using: sort_merged_arrays
- works on Puppet 5
- fails on Puppet 4

Using: sort_merge_arrays
- fails on Puppet 5
- works on Puppet 4

Any less ugly idea is appretiated.

**Comment by hlindberg** [comment]
@tuxmea Sorry that you ended up in this state because of this bug being fixed.  What is sad is that you started using the misspelled word as the documentation showed the correct spelling. The option "sort_merge_array" never worked (and never will), it just did not fail (there was never any sorting taking place). You could just remove the misspelled option all together and start using the correctly spelled word in newer versions.

**Comment by alvagante** [comment]
+1 for removing the option from hiera config, until we will drop support for Puppet < 4.10.4 and avoid to pollute the hierarchy with the porkaround.

**Pull request merged**
